RewslyERG/config/routes.rb
RewslyERG::Application.routes.draw do

   root 'stories#index'

   get "/search", to: "stories#search"

   resources :stories

 

end

RewslyERG/app/models/story.rb
class Story < ActiveRecord::Base
	validates :title, :link, :upvotes, :category, presence: true
	validates :link, :format => URI::regexp(%w(http https))
	validates :upvotes, numericality: {only_integer: true}
	validates :category, length: {minimum: 5}


	def self.search_for(query)
		where('title LIKE ? OR category LIKE ?  OR upvotes LIKE ?', "%#{query}%", "%#{query}%", "%#{query}%")
	end
end

RewslyERG/app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	def index
		@stories = Story.all
	end

	def search
		query = params[:q]
 		@stories = Story.search_for(query)
	end


	def new
		@stories = Story.new
	end

	def show 
		@stories = Story.find(params[:id])
  		rescue 
  		redirect_to root_path
	end

	def create 
		 safe_params = params.require('story').permit(:title, :link, :upvotes, :category)
  	 	@stories = Story.create(safe_params)
  	 	if @stories.save
  	     redirect_to @stories
       else
        render 'new'
      end
	end

	def edit
    	@stories = Story.find(params[:id])
  	end

  	def update 
    safe_params = params.require('story').permit(:title, :link, :upvotes, :category)
    @stories = Story.find(params[:id])
    @stories.update params.require('story').permit(:title, :link, :upvotes, :category)
    redirect_to @stories
  end

end

RewslyERG/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RewslyERG</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

RewslyERG/app/views/stories/_list.html.erb
<% @stories.each do |story| %>
	<section>
		<h3><%= story.title %></h3>
		<p><%= story.category %></p>
		<p><%= story.upvotes %></p>
		<p><%= link_to "Read More", story.link %></p>
	
		</br>
		<%= link_to "Show", story %>

	</section>

<%end%>

RewslyERG/app/views/stories/_search.html.erb
<%= form_tag "/search", method: "GET" do %>
	<%= label_tag :q, "Search"%>
	<%= text_field_tag :q %>
	<%= submit_tag "Search Stories" %>
<% end %>

RewslyERG/app/views/stories/edit.html.erb
<% if @stories.errors.any? %>
	<h2>There were errors saving your story.</h2>

	<ul>
		<% @stories.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<%end%>
	</ul>
<%end%>


<%= form_for @stories do |f| %>
	<%= f.label  :title %>
	<%= f.text_field  :title %>
	<%= f.label  :link %>
	<%= f.text_field  :link %>
	<%= f.label  :upvotes %>
	<%= f.text_field  :upvotes %>
	<%= f.label  :category %>
	<%= f.text_field  :category %>
	<%= f.submit "Add Story" %>
<% end %>

RewslyERG/app/views/stories/index.html.erb
<h1>Welcome to Rewsly. It will get interesting, I swear.</h1>

<h2>These are real life stories from the interwebs. </h2>

<%= render "search" %>

</br>

<%=link_to "Add New StRory", 'stories/new' %>

</br>

<%= render "list" %>

RewslyERG/app/views/stories/new.html.erb
<% if @stories.errors.any? %>
	<h2>There were errors saving your story.</h2>

	<ul>
		<% @stories.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<%end%>
	</ul>
<%end%>


<%= form_for @stories do |f| %>
	<%= f.label  :title %>
	<%= f.text_field  :title %>
	<%= f.label  :link %>
	<%= f.text_field  :link %>
	<%= f.label  :upvotes %>
	<%= f.text_field  :upvotes %>
	<%= f.label  :category %>
	<%= f.text_field  :category %>
	<%= f.submit "Add Story" %>
<% end %>

RewslyERG/app/views/stories/search.html.erb
<h1>StRory Search Results</h1>

<%= render "search" %>

<%= link_to "Back", root_url %>

<%= render "list" %>

RewslyERG/app/views/stories/show.html.erb
<h2>Youe new StRory is:</h2>

	<section>
		<h3><%= @stories.title %></h3>
		<p><%= @stories.category %></p>
		<p><%= @stories.upvotes %></p>
		<p><%= link_to "Read More", @stories.link %></p>
	</section>

</br>
<%=link_to "StRory List", root_path %>
</br>
<%= link_to "Edit", edit_story_path(@stories) %>